### ISSUE TITLE
Trace View supports jlink RTT

### ISSUE THREAD

**Issue by hongshui3000** [klonyyy/STMViewer#25]
jlink RTT is more efficient than SWO

**Comment by klonyyy** [comment]
Could you elaborate and provide some more info why is it more efficient in the way SWO is used in Trace Viewer?

**Comment by hongshui3000** [comment]
![image](https://github.com/klonyyy/STMViewer/assets/25566498/8de935d4-9ea1-49a9-ab82-96f10196073d)
https://www.segger.com/products/debug-probes/j-link/technology/about-real-time-transfer/

**Comment by Candas1** [comment]
I am not sure you can compare RTT and SWO like that for this use case.
RTT is basically working like the Variable Viewer, you are polling the memory in an asynchronous way.
With SWO you are pushing the data out in a synchronous way.

**Comment by klonyyy** [comment]
I don't think it would be better than SWO **in the way it is used in Trace Viewer**. This is not only about the update rate, but also the way the data is sent compared to RTT. SWO is synchronous, meaning you do not wait for the debugger to poll for RAM data. When you make a register write a sample is created with a realtive timestamp attached to it and then sent using SWO. This is why it is a great tool for measuring performance of functions/interrupts, since you can be sure about the time each sample was created (as opposed to Variable Viewer or RTT which are asynchronous and you only see the timepoints the RAM memory was sampled by the debug probe).

**Comment by hongshui3000** [comment]
RTT does require polling to get data, but SWO requires the MCU to put the characters that need to be output into the register and wait for the transmission to complete, which may block the program during this period. The biggest difference between RTT and SWO is that the sending buffer becomes larger. RTT can also add time information to the data frame that needs to be output. Of course, the processing will be more complicated than SWO.

**Comment by klonyyy** [comment]
Ok, but again this has a more of a Variable Viewer-like application than Trace Viewer. You have to know that Trace Viewer is not about sending strings, but rather utilize the bus as efficiently as possible with single bytes used as flags to describe logic levels. And since RTT is also implemented in target software it is less convenient, more intrusive, and it is impossible to be more efficient than SWO in this task since the timestamps are added on the level of hardware peripheral, not software.
